### ISSUE TITLE
Asking questions about type mismatches

### ISSUE THREAD

**Issue by jnchzy** [project-everest/hacl-star#141] opened 2019-01-30 08:54 UTC
There are some problems when I tested the curve25519.fst by fstar.exe of  fstar_0.9.6.0_Windows_x64. The type is mismatch. 
  
 (Error 189) Expected expression of type "FStar.UInt128.t"; got expression "a" of type "Hacl.Bignum.Parameters.wide" (see also E:\hacl-star-master\code\curve25519\Hacl.Bignum.Parameters.fst(160,27-160,28))
[0m[31;1m1 error was reported (see above)

Type "Hacl.Bignum.Parameters.wide"  is hacl.UInt128.t.

How can I convert hacl.UInt128.t to FStar.UInt128.t? or any other advice? Thank you very much!

**Comment by s-zanella** [comment] 2019-01-30 09:42
Duplicate of #137

**Closed by s-zanella** 2019-01-30 09:42 UTC
Labels: duplicate
