### ISSUE TITLE
[$] Enable build system and optimize libintvector.h for PPC64LE Linux

### ISSUE THREAD

**Issue by edelsohn** [project-everest/hacl-star#404] opened 2021-02-17 18:29 UTC
1. Update configuration and build system to allow EverCrypt to build on PPC64LE Linux
2. Implement and optimize libintvector.h vector instruction abstraction for IBM Power VSX (Power9)
3. Update EverCrypt to utilize vectorized implementation on PPC64LE Linux
4. Update OCaml bindings for PPC64LE Linux

**Comment by MrDracoG** [comment] 2021-06-27 19:17
What still needs to be done for this issue?

**Comment by edelsohn** [comment] 2021-06-27 20:20
This now is complete although there is a minor correction to the Power9 compiler options that is under discussion.

**Comment by MrDracoG** [comment] 2021-06-27 20:57
Ok, that's what I figured. Thanks for the response.

**Comment by Kachoc** [comment] 2021-06-28 08:28
Closing the issue as the issue is now considered solved, following @edelsohn 's mail confirmation.

**Closed by Kachoc** 2021-06-28 08:28 UTC
Labels: P3, build, enhancement, feature request
