### ISSUE TITLE
There are some questions for testing curve25519.fst.

### ISSUE THREAD

**Issue by jnchzy** [project-everest/hacl-star#135] opened 2018-12-29 03:59 UTC
There were some problems when I tested the file by fstar.exe.The errors are showed in the following figure. I don't know the reason. I am looking forward for your answer. Thank you very much.
![image](https://user-images.githubusercontent.com/20393374/50533263-3dea2880-0b61-11e9-9415-bc210bdba10f.png)

**Comment by beurdouche** [comment] 2019-01-03 11:21
Hi, please make sure you are using F* and Kremlin on their `stable` branches and this should work.

**Comment by jnchzy** [comment] 2019-01-09 06:46
Thank you very much. I have replaced fstar.exe by fstar_0.9.6.0_Windows_x64. Before I used fstar.exe of fstar_0.9.5.0_Windows_x64. But there are still some questions. The errors are showed in the following figure. I don't know the reason. I am looking forward for your answer. Thank you very much. 
![image](https://user-images.githubusercontent.com/20393374/50881657-4e31bb80-141d-11e9-95be-adbbe488c027.png)

**Comment by s-zanella** [comment] 2019-01-30 09:44
The last question is a duplicate of #137

**Closed by s-zanella** 2019-01-30 09:44 UTC
Labels: question
