### ISSUE TITLE
Bytecode linking fails due to undefined symbol

### ISSUE THREAD

**Issue by camlspotter** [project-everest/hacl-star#375] opened 2020-10-13 23:48 UTC
A library using `hacl-star` fails when byte-compiling a test program.  A small repro case:

---------------

```
(* a.ml *)
module X = Hacl_star
```

```
(executables (modes byte exe) (public_names a) (libraries hacl-star))
```

```
$ dune exec ./a.exe
# no progblem

$ dune exec ./a.bc
File "_none_", line 1:
Error: Error on dynamically loaded library: /.../.opam/default/lib/stublibs/dllocamlevercrypt.so: /.../.opam/default/lib/stublibs/dllocamlevercrypt.so: undefined symbol: EverCrypt_DRBG_max_personalization_string_length
```

--------------

It seems the problem is in `ocamlevercrypt.cma`:

```
$ ocamlc -o dummy /.../.opam/default/lib/hack-star-raw/ocamlevercrypt.cma
File "_none_", line 1:
Error: Error on dynamically loaded library: /.../.opam/default/lib/stublibs/dllocamlevercrypt.so: /.../.opam/default/lib/stublibs/dllocamlevercrypt.so: undefined symbol: EverCrypt_DRBG_max_personalization_string_length
```

**Comment by msprotz** [comment] 2020-10-14 00:25
Thanks! @victor-dumitrescu has a fix in https://github.com/project-everest/hacl-star/pull/364 that I just merged so it should only be a matter of refreshing the OPAM package now.

Basically you should have the stublibs in your LD_LIBRARY_PATH but since most people don't, we add a spurious -L argument when creating the cma so that ocamlopt passes the right directory later on.

**Comment by camlspotter** [comment] 2020-10-21 03:25
Thanks!

**Comment by camlspotter** [comment] 2021-09-09 11:51
I still see the same issue with hacl-star.0.3.2:

```
$ dune build
Entering directory '/Users/jun/.share/scaml'
File "_none_", line 1:
Error: Error on dynamically loaded library: /Users/jun/.share/scaml/_opam/lib/stublibs/dllocamlevercrypt.so: dlopen(/Users/jun/.share/scaml/_opam/lib/stublibs/dllocamlevercrypt.so, 10): Library not loaded: libevercrypt.so
  Referenced from: /Users/jun/.share/scaml/_opam/lib/stublibs/dllocamlevercrypt.so
  Reason: image not found
```

**Comment by victor-dumitrescu** [comment] 2021-09-09 15:26
Hi, thanks for the report. I can't reproduce this on my machine and I'm wondering if this could have something to do with your opam context. Could you please see if you get the same error trying this in a fresh opam switch?

**Comment by beurdouche** [comment] 2022-01-20 17:24
@victor-dumitrescu Could you triage this please? (keep open, close, set appropriate labels). Thanks a lot!

**Comment by victor-dumitrescu** [comment] 2022-01-20 17:44
I'm going to close it since there hasn't been any activity in a while and I couldn't reproduce but feel free to reopen if you're still having this issue. Thanks!

**Closed by victor-dumitrescu** 2022-01-20 17:44 UTC
